<a href="https://colab.research.google.com/github/hemsush/MLprojects/blob/main/Linear_Regression_extended_temp_humidity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression


In [15]:

# X-  year,temp,percentage of humidity, Y -co2 level x= [year,temperature,percentage of humidity]
x = np.array([[2000,30,86],[2001,21,87],[2002,22,85]])
y = [123,456,767]



In [27]:
x_train=np.array(x)
x_test=np.array(x)

In [28]:
y_train=np.array(y)
y_test=np.array(y)

In [24]:
print(x_train)

[[2000   30   86]
 [2001   21   87]
 [2002   22   85]]


In [25]:
model = LinearRegression()
model.fit(x_train,y_train) # for training


LinearRegression()

In [29]:
model.predict(x_test)

array([123., 456., 767.])